# Generated by Django 3.1.1 on 2020-09-03 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200902_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(max_length=240)),
                ('ticket_status', models.CharField(choices=[('New', 'New'), ('IP', 'In Progress'), ('Done', 'Done'), ('Invalid', 'Invalid')], default='New', max_length=15)),
                ('ticket_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_author', to=settings.AUTH_USER_MODEL)),
                ('user_assigned_to_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_assigned_to_ticket', to=settings.AUTH_USER_MODEL)),
                ('user_completed_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_completed_ticket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
